Spring Data with Hibernate
andriiyan/Spring-Data-Access pull request #8
Opened 2022-05-06 13:35 UTC by andriiyan

2022-05-09 11:37 UTC, eugenicon commented
Please add some initial data population. This feature may be enabled by property or separate application profile

2022-05-09 14:12 UTC, eugenicon requested changes
All-and-all, this is pretty interesting solution, however there's one essential point missing here - spring-data almost not used. ServiceRegistry, session factory and CriteriaBuilder are core-hibernate. Implementing CrudRepository and correctly configuring spring data is capeable of much more! Please review https://learn.epam.com/detailsPage?id=3374f018-bda4-4b86-8657-bffcdbbeb538 for guidelines

2022-05-09 14:12 UTC, eugenicon commented on src/main/java/com/github/andriiyan/spring_data_access/impl/dao/BaseDao.java
> +            }
Extract this repetitive part of code to a separate method and reuse in saveAll

2022-05-09 14:12 UTC, eugenicon commented on src/main/java/com/github/andriiyan/spring_data_access/api/dao/EventDao.java
> +public interface EventDao extends CrudRepository<Event, Long> {
CrudRepository should be parametrized with exact entity type - EventEntity in this case

2022-05-09 14:12 UTC, eugenicon commented on src/main/java/com/github/andriiyan/spring_data_access/impl/service/EventServiceImpl.java
> +        final Event event = eventDao.findById(eventId).get();
This can potentially throw an unhandled exception

2022-05-09 14:12 UTC, eugenicon commented on src/main/resources/application.xml
> +    <bean id="userAccountService" class="com.github.andriiyan.spring_data_access.impl.service.UserAccountServiceImpl">
You use xml config, so please remove all @Autowired annotations. It's one way or another

2022-05-09 14:12 UTC, eugenicon commented on src/main/java/com/github/andriiyan/spring_data_access/impl/dao/BaseDao.java
> +            Transaction transaction = session.beginTransaction();
Transactions are required for modifying operations only

2022-05-09 14:12 UTC, eugenicon commented on src/main/java/com/github/andriiyan/spring_data_access/api/dao/UserAccountDao.java
> +public interface UserAccountDao {
extends CrudRepository<UserAccountEntity, Long>

2022-05-17 19:55 UTC, andriiyan commented on src/main/java/com/github/andriiyan/spring_data_access/impl/service/EventServiceImpl.java
> +        final Event event = eventDao.findById(eventId).get();
Yes, but shouldn't this be handled in the invocation side.

I mean some sort of:

```
try {
    bookingFacade.bookTicket(...) /* which internally uses get() for the Event and UserAccount entities */
} catch (NoSuchElementException e) {
   api.return(400, "Bad request)";
}
```

2022-05-29 11:17 UTC, eugenicon approved these changes

2022-05-29 16:27 UTC, merged